/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SiteRouteImport } from './routes/_site'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as SiteIndexRouteImport } from './routes/_site.index'
import { Route as AdminAuthenticatedRouteImport } from './routes/admin/_authenticated'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as SiteBlogIndexRouteImport } from './routes/_site.blog.index'
import { Route as SiteBlogSlugRouteImport } from './routes/_site.blog.$slug'
import { Route as SiteCardsIndexRouteImport } from './routes/_site.cards.index'
import { Route as SiteCardsSlugRouteImport } from './routes/_site.cards.$slug'
import { Route as SiteCountriesIndexRouteImport } from './routes/_site.countries.index'
import { Route as SiteCountriesSlugRouteImport } from './routes/_site.countries.$slug'
import { Route as AdminAuthenticatedIndexRouteImport } from './routes/admin/_authenticated.index'

const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRoute,
} as any)
const AdminAuthenticatedRoute = AdminAuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const SiteBlogIndexRoute = SiteBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteBlogSlugRoute = SiteBlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => SiteRoute,
} as any)
const SiteCardsIndexRoute = SiteCardsIndexRouteImport.update({
  id: '/cards/',
  path: '/cards/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteCardsSlugRoute = SiteCardsSlugRouteImport.update({
  id: '/cards/$slug',
  path: '/cards/$slug',
  getParentRoute: () => SiteRoute,
} as any)
const SiteCountriesIndexRoute = SiteCountriesIndexRouteImport.update({
  id: '/countries/',
  path: '/countries/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteCountriesSlugRoute = SiteCountriesSlugRouteImport.update({
  id: '/countries/$slug',
  path: '/countries/$slug',
  getParentRoute: () => SiteRoute,
} as any)
const AdminAuthenticatedIndexRoute = AdminAuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminAuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof SiteIndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/blog/$slug': typeof SiteBlogSlugRoute
  '/cards/$slug': typeof SiteCardsSlugRoute
  '/countries/$slug': typeof SiteCountriesSlugRoute
  '/blog/': typeof SiteBlogIndexRoute
  '/cards/': typeof SiteCardsIndexRoute
  '/countries/': typeof SiteCountriesIndexRoute
  '/admin/': typeof AdminAuthenticatedIndexRoute
}
export interface FileRoutesByTo {
  '/admin': typeof AdminAuthenticatedIndexRoute
  '/admin/login': typeof AdminLoginRoute
  '/': typeof SiteIndexRoute
  '/blog/$slug': typeof SiteBlogSlugRoute
  '/cards/$slug': typeof SiteCardsSlugRoute
  '/countries/$slug': typeof SiteCountriesSlugRoute
  '/blog': typeof SiteBlogIndexRoute
  '/cards': typeof SiteCardsIndexRoute
  '/countries': typeof SiteCountriesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_site': typeof SiteRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/admin/_authenticated': typeof AdminAuthenticatedRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/_site/': typeof SiteIndexRoute
  '/_site/blog/$slug': typeof SiteBlogSlugRoute
  '/_site/cards/$slug': typeof SiteCardsSlugRoute
  '/_site/countries/$slug': typeof SiteCountriesSlugRoute
  '/_site/blog/': typeof SiteBlogIndexRoute
  '/_site/cards/': typeof SiteCardsIndexRoute
  '/_site/countries/': typeof SiteCountriesIndexRoute
  '/admin/_authenticated/': typeof AdminAuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/login'
    | '/blog/$slug'
    | '/cards/$slug'
    | '/countries/$slug'
    | '/blog/'
    | '/cards/'
    | '/countries/'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/admin'
    | '/admin/login'
    | '/'
    | '/blog/$slug'
    | '/cards/$slug'
    | '/countries/$slug'
    | '/blog'
    | '/cards'
    | '/countries'
  id:
    | '__root__'
    | '/_site'
    | '/admin'
    | '/admin/_authenticated'
    | '/admin/login'
    | '/_site/'
    | '/_site/blog/$slug'
    | '/_site/cards/$slug'
    | '/_site/countries/$slug'
    | '/_site/blog/'
    | '/_site/cards/'
    | '/_site/countries/'
    | '/admin/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SiteRoute: typeof SiteRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/admin/_authenticated': {
      id: '/admin/_authenticated'
      path: ''
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAuthenticatedRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_site/blog/': {
      id: '/_site/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof SiteBlogIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/blog/$slug': {
      id: '/_site/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof SiteBlogSlugRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/cards/': {
      id: '/_site/cards/'
      path: '/cards'
      fullPath: '/cards/'
      preLoaderRoute: typeof SiteCardsIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/cards/$slug': {
      id: '/_site/cards/$slug'
      path: '/cards/$slug'
      fullPath: '/cards/$slug'
      preLoaderRoute: typeof SiteCardsSlugRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/countries/': {
      id: '/_site/countries/'
      path: '/countries'
      fullPath: '/countries/'
      preLoaderRoute: typeof SiteCountriesIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/countries/$slug': {
      id: '/_site/countries/$slug'
      path: '/countries/$slug'
      fullPath: '/countries/$slug'
      preLoaderRoute: typeof SiteCountriesSlugRouteImport
      parentRoute: typeof SiteRoute
    }
    '/admin/_authenticated/': {
      id: '/admin/_authenticated/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAuthenticatedIndexRouteImport
      parentRoute: typeof AdminAuthenticatedRoute
    }
  }
}

interface SiteRouteChildren {
  SiteIndexRoute: typeof SiteIndexRoute
  SiteBlogSlugRoute: typeof SiteBlogSlugRoute
  SiteCardsSlugRoute: typeof SiteCardsSlugRoute
  SiteCountriesSlugRoute: typeof SiteCountriesSlugRoute
  SiteBlogIndexRoute: typeof SiteBlogIndexRoute
  SiteCardsIndexRoute: typeof SiteCardsIndexRoute
  SiteCountriesIndexRoute: typeof SiteCountriesIndexRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteIndexRoute: SiteIndexRoute,
  SiteBlogSlugRoute: SiteBlogSlugRoute,
  SiteCardsSlugRoute: SiteCardsSlugRoute,
  SiteCountriesSlugRoute: SiteCountriesSlugRoute,
  SiteBlogIndexRoute: SiteBlogIndexRoute,
  SiteCardsIndexRoute: SiteCardsIndexRoute,
  SiteCountriesIndexRoute: SiteCountriesIndexRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

interface AdminAuthenticatedRouteChildren {
  AdminAuthenticatedIndexRoute: typeof AdminAuthenticatedIndexRoute
}

const AdminAuthenticatedRouteChildren: AdminAuthenticatedRouteChildren = {
  AdminAuthenticatedIndexRoute: AdminAuthenticatedIndexRoute,
}

const AdminAuthenticatedRouteWithChildren =
  AdminAuthenticatedRoute._addFileChildren(AdminAuthenticatedRouteChildren)

interface AdminRouteChildren {
  AdminAuthenticatedRoute: typeof AdminAuthenticatedRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuthenticatedRoute: AdminAuthenticatedRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SiteRoute: SiteRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
